# Generated by Django 5.2 on 2025-04-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnquiry',
            fields=[
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(default='new', max_length=20)),
                ('query_id', models.CharField(default='20250426041400331747', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
