# Generated by Django 5.2 on 2025-04-28 15:48

import enquiry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='query_id',
            field=models.CharField(default=enquiry.models.getQueryID, max_length=30, primary_key=True, serialize=False),
        ),
    ]
